

const books = [
    {
      id: 'b1',
      title: 'To Kill a Mockingbird',
      author: 'Harper Lee',
      publish_year: 1960,
      summary: 'The unforgettable novel of a childhood in a sleepy Southern town and the crisis of conscience that rocked it.',
      genre: 'Classic Literature',
      image: "",
      isbn: '978-0446310789',
    },
    {
      id: 'b2',
      title: '1984',
      author: 'George Orwell',
      publish_year: 1949,
      summary: 'A dystopian novel set in Airstrip One, formerly Great Britain, a province of the superstate Oceania.',
      genre: 'Science Fiction',
      image: "",
      isbn: '978-0451524935',
    },
    {
      id: 'b3',
      title: 'Pride and Prejudice',
      author: 'Jane Austen',
      publish_year: 1813,
      summary: 'The story follows the main character, Elizabeth Bennet, as she deals with issues of manners, upbringing, morality, education, and marriage.',
      genre: 'Classic Literature',
      image: "",
      isbn: '978-1503290563',
    },
    {
      id: 'b4',
      title: 'The Great Gatsby',
      author: 'F. Scott Fitzgerald',
      publish_year: 1925,
      summary: 'A novel of the Roaring Twenties that shines a spotlight on the empty lives of the US upper class.',
      genre: 'Classic Literature',
      image: "",
      isbn: '978-0743273565',
    },
    {
      id: 'b5',
      title: 'The Catcher in the Rye',
      author: 'J.D. Salinger',
      publish_year: 1951,
      summary: 'A rebellious teenager, Holden Caulfield, navigates his way through the complexities of adolescence.',
      genre: 'Fiction',
      image: "",
      isbn: '978-0316769488',
    },
    {
      id: 'b6',
      title: 'Moby Dick',
      author: 'Herman Melville',
      publish_year: 1851,
      summary: 'Captain Ahab’s quest for the white whale is a timeless epic—a stirring tragedy of vengeance and obsession.',
      genre: 'Classic Literature',
      image: "",
      isbn: '978-1503280786',
    },
    {
      id: 'b7',
      title: 'War and Peace',
      author: 'Leo Tolstoy',
      publish_year: 1869,
      summary: 'A complex tale of families in Russia during the Napoleonic Era.',
      genre: 'Historical Fiction',
      image: "",
      isbn: '978-1400079988',
    },
    {
      id: 'b8',
      title: 'The Lord of the Rings',
      author: 'J.R.R. Tolkien',
      publish_year: 1954,
      summary: 'An epic fantasy trilogy featuring a struggle between good and evil in a mythical world.',
      genre: 'Fantasy',
      image: "",
      isbn: '978-0544003415',
    },
    {
      id: 'b9',
      title: 'The Alchemist',
      author: 'Paulo Coelho',
      publish_year: 1988,
      summary: 'A young Andalusian shepherd in search of a dream and his personal legend.',
      genre: 'Fiction',
      image: "",
      isbn: '978-0062315007',
    },
    {
      id: 'b10',
      title: 'Harry Potter and the Philosopher\'s Stone',
      author: 'J.K. Rowling',
      publish_year: 1997,
      summary: 'Harry Potter, a boy who learns on his eleventh birthday that he is the orphaned son of two powerful wizards.',
      genre: 'Fantasy',
      image: "",
      isbn: '978-0747532699',
    }
];

export default books;
